cmake_minimum_required(VERSION 3.20)

if(NOT license_output OR NOT agent_source OR NOT aria_source)
    message(FATAL_ERROR "license_output, agent_source and aria_source are required")
endif()
file(MAKE_DIRECTORY "${license_output}")
file(LOCK "${license_output}/.stage.lock" GUARD PROCESS TIMEOUT 120)
foreach(component ariaagent aria json mira openssl)
    file(REMOVE_RECURSE "${license_output}/${component}")
endforeach()
foreach(component ariaagent aria)
    if(component STREQUAL "ariaagent")
        set(source "${agent_source}")
    else()
        set(source "${aria_source}")
    endif()
    foreach(document LICENSE THIRD_PARTY_NOTICES.md)
        if(EXISTS "${source}/${document}")
            configure_file("${source}/${document}" "${license_output}/${component}/${document}" COPYONLY)
        else()
            message(WARNING "Selected ${component} lacks ${document}; obtain matching materials before distribution")
        endif()
    endforeach()
endforeach()

foreach(component json mira openssl)
    set(source "${${component}_source}")
    if(component STREQUAL "json")
        set(license LICENSE.MIT)
    elseif(component STREQUAL "openssl")
        set(license LICENSE.txt)
    else()
        set(license LICENSE)
    endif()
    if(NOT source OR NOT EXISTS "${source}/${license}")
        message(WARNING "Selected ${component} has no known source license; supply matching license/notices before distribution")
        continue()
    endif()
    configure_file("${source}/${license}" "${license_output}/${component}/${license}" COPYONLY)
    file(GLOB notices "${source}/NOTICE*" "${source}/THIRD_PARTY_NOTICES*")
    foreach(notice IN LISTS notices)
        if(NOT IS_DIRECTORY "${notice}")
            file(COPY "${notice}" DESTINATION "${license_output}/${component}")
        endif()
    endforeach()
    if(component STREQUAL "json")
        file(GLOB_RECURSE headers "${source}/include/nlohmann/*.hpp")
        set(attributions "")
        foreach(header IN LISTS headers)
            file(STRINGS "${header}" lines ENCODING UTF-8
                REGEX "SPDX-(FileCopyrightText|License-Identifier):")
            list(APPEND attributions ${lines})
        endforeach()
        list(REMOVE_DUPLICATES attributions)
        list(SORT attributions)
        string(JOIN "\n" attributions ${attributions})
        file(WRITE "${license_output}/json/ATTRIBUTIONS.txt" "${attributions}\n")
    endif()
endforeach()
